networks:
  oc_network:
    driver: bridge

services:
  postgres:
    image: postgres:17
    container_name: optic_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${PWD}/.docker/db_data:/var/lib/postgresql/data
    networks:
      - oc_network

  java:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: ${BUILD_TARGET:-dev}
    container_name: optic_console_java
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    ports:
      - "${BACKEND_PORT}:8080"
      - "5005:5005"  # For remote debugging
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=dev,${SPRING_PROFILES_ACTIVE}
    networks:
      - oc_network

volumes:
  pg_data:
