networks:
  oc_network:
    driver: bridge

services:
  postgres:
    image: postgres:17
    container_name: optic_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${PWD}/.docker/db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 25s
      retries: 1
    networks:
      - oc_network

  java:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: ${BUILD_TARGET:-dev}
    container_name: optic_console_java
    volumes:
      - .:/app
      - m2-cache:/root/.m2  # Cache Maven dependencies
    ports:
      - "${BACKEND_PORT}:8080"
      - "5005:5005"  # For remote debugging
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # JDWP: configure debugger only here to avoid duplicates
#      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
      # Ensure other common sources don't re-inject
      JDK_JAVA_OPTIONS: ""
      MAVEN_OPTS: ""
      JAVA_OPTS: ""
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - oc_network

volumes:
  m2-cache:
  pg_data:
